option.exclude_paths = ["lab*/*\\.sim/.*"]
option.textwidth = 160
textrules.style_textwidth = true
textrules.style_semicolon = true
option.indent = 2
syntaxrules.tab_character = true
syntaxrules.style_indent = true