line-length = 160
indent-width = 2
target-version = "py310"
preview = true

[lint]
# 1. Enable flake8-bugbear (`B`) rules, in addition to the defaults.
select = ["NPY", "PERF", "E1", "E4", "E7", "E9", "I002", "TID252", "W", "C4", "C901", "F", "FBT", "B", "Q", "DTZ", "RSE", "RET", "ARG", "SLF", "SIM", "PLE", "PLW", "PLR"]

# 2. Avoid enforcing line-length violations (`E501`)
ignore = ["E111","E501"]

[format]
# 5. Use single quotes for non-triple-quoted strings.
quote-style = "double"

[lint.isort]
case-sensitive = true
combine-as-imports = true

[lint.pylint]
max-args = 12
max-bool-expr = 8
max-returns = 8
max-public-methods = 30