[doc]
name = "report-lab2"
bundle = "https://data1.fullyjustified.net/tlextras-2022.0r0.tar"

[[output]]
name = "index"
type = "pdf"
inputs = [
    "_preamble.tex",
    "index.tex",
    "_postamble.tex",
]
